---
- name: "Create {{ prometheus_base_install_dir }}"
  file:
    path: "{{ prometheus_base_install_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Ensure Firewalld is installed"
  package:
    name: firewalld
    state: latest

- name: "Ensure Firewalld is running and enabled"
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Install Prometheus
  include: prometheus.yml
  when: prometheus_install

- name: Install Prometheus node exporter
  include: node_exporter.yml
  when: prometheus_node_exporter_install

- name: Install Prometheus alert manager
  include: alert_manager.yml
  when: prometheus_alert_manager_install

- name: Install Pushgateway
  include: push_gateway.yml
  when: prometheus_push_gateway_install

- name: Install Prometheus SNMP exporter
  include: snmp_exporter.yml
  when: prometheus_snmp_exporter_install

- name: Install Prometheus Blackbox exporter
  include: blackbox_exporter.yml
  when: prometheus_blackbox_exporter_install
