---
- name: "daemon-reload"
  systemd:
    daemon-reload: yes

#- name: "configure prometheus"
#  template:
#    src: "{{ prometheus_server_conf_template_src }}"
#    dest: "{{ prometheus_server_conf_dst }}"
#    owner: "{{ prometheus_service_user }}"
#    group: "{{ prometheus_service_group }}"
#    mode: 0660
#  delegate_to: "{{ prometheus_server_fqdn }}"
#  listen: "reconfigure prometheus"
#
#- name: "restart prometheus"
#  service:
#    name: "{{ prometheus_service_name }}"
#    state: restarted
#    enabled: yes
#  delegate_to: "{{ prometheus_server_fqdn }}"
#  listen: "reconfigure prometheus"


- name: restart prometheus
  service: name=prometheus state=restarted enabled=yes

- name: stop prometheus
  service: name=prometheus state=stopped

- name: start prometheus
  service: name=prometheus state=started

- name: restart node_exporter
  service: name=node_exporter state=restarted enabled=yes

- name: stop node_exporter
  service: name=node_exporter state=stopped

- name: start node_exporter
  service: name=node_exporter state=started

- name: restart alertmanager
  service: name=alertmanager state=restarted enabled=yes

- name: stop alertmanager
  service: name=alertmanager state=stopped

- name: start alertmanager
  service: name=alertmanager state=started

- name: restart pushgateway
  service: name=pushgateway state=restarted enabled=yes

- name: stop pushgateway
  service: name=pushgateway state=stopped

- name: start pushgateway
  service: name=pushgateway state=started

- name: restart snmp_exporter
  service: name=snmp_exporter state=restarted enabled=yes

- name: stop snmp_exporter
  service: name=snmp_exporter state=stopped

- name: start snmp_exporter
  service: name=snmp_exporter state=started

- name: restart blackbox_exporter
  service: name=blackboxexporter state=restarted enabled=yes

- name: stop blackbox_exporter
  service: name=blackboxexporter state=stopped

- name: start blackbox_exporter
  service: name=blackboxexporter state=started

- name: reload blackbox_exporter
  service: name=blackboxexporter state=reloaded
